apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: second-app
  ports:
    - protocol: TCP
      # il servizio espone la 80 e la mappa alla 8080 del container
      port: 80
      targetPort: 8080
